export const initialShapes = [
  {
    x: 10,
    y: 10,
    width: 100,
    height: 100,
    fill: 'red',
    id: 'rect1',
    type: 'rect',
  },
  {
    x: 150,
    y: 150,
    radiusX: 50,
    radiusY: 25,
    stroke: 'black',
    strokeWidth: 2,
    id: 'ellipse1',
    type: 'ellipse',
  },
  {
    x: 300,
    y: 100,
    width: 150,
    height: 75,
    stroke: 'blue',
    strokeWidth: 2,
    id: 'rect2',
    type: 'rect',
  },
  {
    points: [250, 100, 350, 200],
    pointerLength: 10,
    pointerWidth: 10,
    fill: 'black',
    stroke: 'black',
    strokeWidth: 4,
    id: 'arrow1',
    type: 'arrow',
  },
];